// ============================================
// PERFORMANCE TUNING GENERATOR WITH SERVICES
// Append this to optimizer.js or merge manually
// ============================================

function generatePerformanceScript(restore = false) {
    const options = {
        visual: document.getElementById('perf-visual').checked,
        indexing: document.getElementById('perf-indexing').checked,
        superfetch: document.getElementById('perf-superfetch').checked,
        hibernation: document.getElementById('perf-hibernation').checked,
        gameMode: document.getElementById('perf-gamemode').checked
    };
    
    // Get selected services
    const services = {
        diagtrack: document.getElementById('service-diagtrack').checked,
        dmwappush: document.getElementById('service-dmwappush').checked,
        sysmain: document.getElementById('service-sysmain').checked,
        wsearch: document.getElementById('service-wsearch').checked,
        mapsbroker: document.getElementById('service-mapsbroker').checked,
        xbl: document.getElementById('service-xbl').checked,
        printspooler: document.getElementById('service-printspooler').checked,
        fax: document.getElementById('service-fax').checked
    };
    
    const totalSelected = Object.values(options).filter(Boolean).length + Object.values(services).filter(Boolean).length;
    
    if (totalSelected === 0) {
        showNotification('⚠️ Please select at least one performance optimization!', 'warning');
        return;
    }
    
    const script = `# Windows 11 Performance Tuning & Service Optimizer
# Generated: ${new Date().toLocaleString()}
# Mode: ${restore ? 'RESTORE DEFAULTS' : 'OPTIMIZE FOR PERFORMANCE'}
# Generated by Windows 11 Optimization Portal

#Requires -RunAsAdministrator

Write-Host ""
Write-Host "╔════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║      Performance ${restore ? 'Restore' : 'Optimizer'} & Service Manager       ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# Create restore point
Write-Host "📌 Creating system restore point..." -ForegroundColor Yellow
try {
    Enable-ComputerRestore -Drive "C:\\" -ErrorAction SilentlyContinue
    Checkpoint-Computer -Description "Before Performance Changes - $(Get-Date -Format 'yyyy-MM-dd HH:mm')" -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
    Write-Host "   ✓ Restore point created successfully" -ForegroundColor Green
}
catch {
    Write-Host "   ⚠️  Warning: Could not create restore point" -ForegroundColor Yellow
}
Write-Host ""

$changesApplied = 0
$changesFailed = 0

${options.visual ? `
# ${restore ? 'Restore' : 'Optimize'} Visual Effects
Write-Host "───────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host "🎨 ${restore ? 'Restoring' : 'Optimizing'} visual effects..." -ForegroundColor Yellow
try {
    Set-ItemProperty -Path "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced" -Name "TaskbarAnimations" -Type DWord -Value ${restore ? '1' : '0'} -ErrorAction Stop
    Set-ItemProperty -Path "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced" -Name "ListviewAlphaSelect" -Type DWord -Value ${restore ? '1' : '0'} -ErrorAction Stop
    Set-ItemProperty -Path "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced" -Name "ListviewShadow" -Type DWord -Value ${restore ? '1' : '0'} -ErrorAction Stop
    Set-ItemProperty -Path "HKCU:\\Software\\Microsoft\\Windows\\DWM" -Name "EnableAeroPeek" -Type DWord -Value ${restore ? '1' : '0'} -ErrorAction Stop
    Write-Host "   ✓ Visual effects ${restore ? 'restored' : 'disabled for better performance'}" -ForegroundColor Green
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

${options.hibernation ? `
# ${restore ? 'Enable' : 'Disable'} Hibernation
Write-Host "───────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host "💤 ${restore ? 'Enabling' : 'Disabling'} hibernation..." -ForegroundColor Yellow
try {
    ${restore ? 'powercfg /hibernate on' : 'powercfg /hibernate off'}
    Write-Host "   ✓ Hibernation ${restore ? 'enabled' : 'disabled'}${!restore ? ' (hiberfil.sys deleted, disk space freed)' : ''}" -ForegroundColor Green
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

${options.gameMode ? `
# ${restore ? 'Disable' : 'Enable'} Game Mode
Write-Host "───────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host "🎮 ${restore ? 'Disabling' : 'Enabling'} Game Mode..." -ForegroundColor Yellow
try {
    if (-not (Test-Path "HKCU:\\Software\\Microsoft\\GameBar")) {
        New-Item -Path "HKCU:\\Software\\Microsoft\\GameBar" -Force | Out-Null
    }
    Set-ItemProperty -Path "HKCU:\\Software\\Microsoft\\GameBar" -Name "AutoGameModeEnabled" -Type DWord -Value ${restore ? '0' : '1'} -ErrorAction Stop
    Write-Host "   ✓ Game Mode ${restore ? 'disabled' : 'enabled (better gaming & app performance)'}" -ForegroundColor Green
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

# Service Optimizations
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "           WINDOWS SERVICES OPTIMIZATION" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

${services.diagtrack ? `
# Diagnostics Tracking Service
Write-Host "🔧 Optimizing: Diagnostics Tracking Service..." -ForegroundColor Yellow
try {
    Set-Service -Name "DiagTrack" -StartupType ${restore ? 'Automatic' : 'Disabled'} -ErrorAction Stop
    Write-Host "   ✓ DiagTrack set to ${restore ? 'Automatic' : 'Disabled'}" -ForegroundColor Green
    Write-Host "   ℹ️  Less diagnostic data sent to Microsoft" -ForegroundColor Gray
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

${services.dmwappush ? `
# WAP Push Message Routing Service
Write-Host "🔧 Optimizing: WAP Push Message Routing..." -ForegroundColor Yellow
try {
    Set-Service -Name "dmwappushservice" -StartupType ${restore ? 'Automatic' : 'Disabled'} -ErrorAction Stop
    Write-Host "   ✓ dmwappushservice set to ${restore ? 'Automatic' : 'Disabled'}" -ForegroundColor Green
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

${services.sysmain ? `
# Superfetch/SysMain
Write-Host "🔧 Optimizing: Superfetch (SysMain)..." -ForegroundColor Yellow
try {
    Set-Service -Name "SysMain" -StartupType ${restore ? 'Automatic' : 'Disabled'} -ErrorAction Stop
    Write-Host "   ✓ SysMain set to ${restore ? 'Automatic' : 'Disabled'}" -ForegroundColor Green
    ${!restore ? `Write-Host "   ℹ️  Recommended for SSD users (not needed)" -ForegroundColor Gray` : ''}
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

${services.wsearch ? `
# Windows Search
Write-Host "🔧 Optimizing: Windows Search..." -ForegroundColor Yellow
try {
    Set-Service -Name "WSearch" -StartupType ${restore ? 'Automatic' : 'Manual'} -ErrorAction Stop
    Write-Host "   ✓ WSearch set to ${restore ? 'Automatic' : 'Manual'}" -ForegroundColor Green
    ${!restore ? `Write-Host "   ℹ️  Search still works, but won't index in background" -ForegroundColor Gray` : ''}
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

${services.mapsbroker ? `
# Downloaded Maps Manager
Write-Host "🔧 Optimizing: Maps Broker..." -ForegroundColor Yellow
try {
    Set-Service -Name "MapsBroker" -StartupType ${restore ? 'Automatic' : 'Disabled'} -ErrorAction Stop
    Write-Host "   ✓ MapsBroker set to ${restore ? 'Automatic' : 'Disabled'}" -ForegroundColor Green
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

${services.xbl ? `
# Xbox Live Services
Write-Host "🔧 Optimizing: Xbox Live Services..." -ForegroundColor Yellow
try {
    $xblServices = @("XblAuthManager", "XblGameSave", "XboxNetApiSvc")
    foreach ($svc in $xblServices) {
        try {
            Set-Service -Name $svc -StartupType ${restore ? 'Automatic' : 'Manual'} -ErrorAction Stop
        }
        catch {
            # Service might not exist, continue
        }
    }
    Write-Host "   ✓ Xbox Live services set to ${restore ? 'Automatic' : 'Manual'}" -ForegroundColor Green
    ${!restore ? `Write-Host "   ⚠️  Xbox games may not work if these are disabled!" -ForegroundColor Yellow` : ''}
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

${services.printspooler ? `
# Print Spooler
Write-Host "🔧 Optimizing: Print Spooler..." -ForegroundColor Yellow
try {
    Set-Service -Name "Spooler" -StartupType ${restore ? 'Automatic' : 'Manual'} -ErrorAction Stop
    Write-Host "   ✓ Print Spooler set to ${restore ? 'Automatic' : 'Manual'}" -ForegroundColor Green
    ${!restore ? `Write-Host "   ℹ️  Will start automatically when you print" -ForegroundColor Gray` : ''}
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

${services.fax ? `
# Fax Service
Write-Host "🔧 Optimizing: Fax Service..." -ForegroundColor Yellow
try {
    Set-Service -Name "Fax" -StartupType ${restore ? 'Automatic' : 'Disabled'} -ErrorAction Stop
    Write-Host "   ✓ Fax service set to ${restore ? 'Automatic' : 'Disabled'}" -ForegroundColor Green
    $script:changesApplied++
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    $script:changesFailed++
}
` : ''}

Write-Host ""
Write-Host "╔════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║                    SUMMARY                              ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "✓ Changes applied successfully: $changesApplied" -ForegroundColor Green
if ($changesFailed -gt 0) {
    Write-Host "❌ Changes that failed: $changesFailed" -ForegroundColor Red
}
Write-Host ""
Write-Host "⚠️  A restart is recommended for all changes to take effect." -ForegroundColor Yellow
Write-Host ""

$restart = Read-Host "Restart now? (y/n)"
if ($restart -eq 'y' -or $restart -eq 'Y') {
    Write-Host "🔄 Restarting in 10 seconds... (Press Ctrl+C to cancel)" -ForegroundColor Yellow
    Start-Sleep -Seconds 10
    Restart-Computer -Force
}
`;

    const modalContent = `
        <div class="alert ${restore ? 'alert-info' : 'alert-success'}">
            <span class="alert-icon">${restore ? 'ℹ️' : '🎯'}</span>
            <div>
                <strong>${restore ? 'Restore Performance Settings' : 'Performance Optimization'}</strong><br>
                ${restore ? 
                    'This will restore performance settings to Windows defaults.' :
                    'This will optimize Windows for better performance. Great for older hardware or when you need maximum speed.'}
            </div>
        </div>
        
        <div class="alert alert-success">
            <span class="alert-icon">✅</span>
            <div>
                <strong>Selected Optimizations:</strong><br>
                ${options.visual ? '✓ Disable Visual Effects<br>' : ''}
                ${options.indexing ? '✓ Optimize Search Indexing<br>' : ''}
                ${options.superfetch ? '✓ Disable Superfetch<br>' : ''}
                ${options.hibernation ? '✓ Disable Hibernation<br>' : ''}
                ${options.gameMode ? '✓ Enable Game Mode<br>' : ''}
                <br>
                <strong>Selected Services:</strong><br>
                ${services.diagtrack ? '✓ Diagnostics Tracking<br>' : ''}
                ${services.dmwappush ? '✓ WAP Push Routing<br>' : ''}
                ${services.sysmain ? '✓ Superfetch/SysMain<br>' : ''}
                ${services.wsearch ? '✓ Windows Search<br>' : ''}
                ${services.mapsbroker ? '✓ Maps Broker<br>' : ''}
                ${services.xbl ? '✓ Xbox Live Services<br>' : ''}
                ${services.printspooler ? '✓ Print Spooler<br>' : ''}
                ${services.fax ? '✓ Fax Service<br>' : ''}
            </div>
        </div>
        
        <h3>Script Preview:</h3>
        <div class="script-preview">${escapeHtml(script)}</div>
        
        <div class="btn-group">
            <button class="btn btn-success" onclick="downloadScript('Performance${restore ? 'Restore' : 'Optimize'}_${getTimestamp()}.ps1', \`${script.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`)">
                💾 Download Script
            </button>
            <button class="btn btn-secondary" onclick="closeModal()">
                Close Preview
            </button>
        </div>
    `;
    
    showModal(`🎯 Performance ${restore ? 'Restore' : 'Optimizer'} Script Ready`, modalContent);
}

// ============================================
// DISK MAINTENANCE GENERATOR
// ============================================

function generateDiskScript() {
    const options = {
        winsxs: document.getElementById('disk-winsxs').checked,
        updates: document.getElementById('disk-updates').checked,
        logs: document.getElementById('disk-logs').checked,
        drivers: document.getElementById('disk-drivers').checked,
        analyze: document.getElementById('disk-analyze').checked
    };
    
    if (!options.winsxs && !options.updates && !options.logs && !options.drivers && !options.analyze) {
        showNotification('⚠️ Please select at least one disk cleanup option!', 'warning');
        return;
    }
    
    // Warning for driver cleanup
    if (options.drivers) {
        showConfirmation(
            'Confirm Driver Cleanup',
            '<strong>Warning:</strong> You selected "Remove Old Driver Packages".<br><br>This will delete old driver versions, and you won\'t be able to roll back if your current drivers have issues.<br><br>Only proceed if you\'re sure your current drivers are working correctly.',
            () => createDiskScript(options)
        );
        return;
    }
    
    createDiskScript(options);
}

function createDiskScript(options) {
    const script = `# Windows 11 Disk Maintenance & Deep Cleanup
# Generated: ${new Date().toLocaleString()}
# Generated by Windows 11 Optimization Portal

#Requires -RunAsAdministrator

Write-Host ""
Write-Host "╔════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║        Disk Maintenance & Deep Cleanup                 ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

Write-Host "⚠️  WARNING: This process may take 10-20 minutes!" -ForegroundColor Yellow
Write-Host "   Please be patient and do not close this window." -ForegroundColor Gray
Write-Host ""

$totalSpaceFreed = 0

${options.analyze ? `
# Analyze disk space with Disk Cleanup
Write-Host "───────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host "📊 Opening Disk Cleanup analysis..." -ForegroundColor Yellow
Write-Host "   Please review the options and click OK to continue." -ForegroundColor Gray
Write-Host ""

# Run Disk Cleanup wizard
Start-Process -FilePath "cleanmgr.exe" -ArgumentList "/sageset:1" -Wait
Write-Host "   Disk Cleanup configured. Running cleanup..." -ForegroundColor Yellow
Start-Process -FilePath "cleanmgr.exe" -ArgumentList "/sagerun:1" -Wait
Write-Host "   ✓ Disk Cleanup completed!" -ForegroundColor Green
Write-Host ""
` : ''}

${options.winsxs ? `
# Clean Component Store (WinSxS)
Write-Host "───────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host "🗂️  Cleaning Component Store (WinSxS)..." -ForegroundColor Yellow
Write-Host "   This may take 5-10 minutes, please wait..." -ForegroundColor Gray

try {
    $before = (Get-ChildItem -Path "C:\\Windows\\WinSxS" -Recurse -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
    Write-Host "   Current WinSxS size: $([math]::Round($before / 1GB, 2)) GB" -ForegroundColor White
    
    # Clean up the component store
    Write-Host "   Running DISM cleanup (this takes a while)..." -ForegroundColor Yellow
    $dismOutput = Dism.exe /Online /Cleanup-Image /StartComponentCleanup /ResetBase /Quiet
    
    $after = (Get-ChildItem -Path "C:\\Windows\\WinSxS" -Recurse -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
    $freed = $before - $after
    $script:totalSpaceFreed += $freed
    
    Write-Host "   ✓ Component store cleaned!" -ForegroundColor Green
    Write-Host "   New WinSxS size: $([math]::Round($after / 1GB, 2)) GB" -ForegroundColor Green
    Write-Host "   Space freed: $([math]::Round($freed / 1GB, 2)) GB" -ForegroundColor Green
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
}
Write-Host ""
` : ''}

${options.updates ? `
# Remove old Windows Update files
Write-Host "───────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host "🔄 Removing old Windows Update files..." -ForegroundColor Yellow
try {
    $before = (Get-ChildItem -Path "C:\\Windows\\SoftwareDistribution\\Download" -Recurse -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
    
    # Stop Windows Update service
    Stop-Service -Name wuauserv -Force -ErrorAction Stop
    Write-Host "   Windows Update service stopped" -ForegroundColor Gray
    
    # Clear download cache
    Remove-Item -Path "C:\\Windows\\SoftwareDistribution\\Download\\*" -Recurse -Force -ErrorAction SilentlyContinue
    
    # Restart service
    Start-Service -Name wuauserv -ErrorAction Stop
    Write-Host "   Windows Update service restarted" -ForegroundColor Gray
    
    $after = (Get-ChildItem -Path "C:\\Windows\\SoftwareDistribution\\Download" -Recurse -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
    $freed = $before - $after
    $script:totalSpaceFreed += $freed
    
    Write-Host "   ✓ Windows Update cache cleared!" -ForegroundColor Green
    Write-Host "   Space freed: $([math]::Round($freed / 1GB, 2)) GB" -ForegroundColor Green
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    # Try to restart service anyway
    try { Start-Service -Name wuauserv } catch { }
}
Write-Host ""
` : ''}

${options.logs ? `
# Clear old system logs
Write-Host "───────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host "📝 Clearing old system logs..." -ForegroundColor Yellow
try {
    $before = (Get-ChildItem -Path "C:\\Windows\\Logs" -Include "*.log", "*.txt" -Recurse -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
    
    Get-ChildItem -Path "C:\\Windows\\Logs" -Include "*.log", "*.txt" -Recurse -ErrorAction SilentlyContinue |
        Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-30) } |
        Remove-Item -Force -ErrorAction SilentlyContinue
    
    $after = (Get-ChildItem -Path "C:\\Windows\\Logs" -Include "*.log", "*.txt" -Recurse -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
    $freed = $before - $after
    $script:totalSpaceFreed += $freed
    
    Write-Host "   ✓ Old log files removed (kept last 30 days)" -ForegroundColor Green
    Write-Host "   Space freed: $([math]::Round($freed / 1GB, 2)) GB" -ForegroundColor Green
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
}
Write-Host ""
` : ''}

${options.drivers ? `
# Remove old driver packages (CAUTION)
Write-Host "───────────────────────────────────────────────────────" -ForegroundColor Gray
Write-Host "🔌 Removing old driver packages..." -ForegroundColor Yellow
Write-Host "   ⚠️  Note: You won't be able to roll back drivers after this!" -ForegroundColor Yellow
try {
    Write-Host "   Running pnputil to remove old drivers..." -ForegroundColor Gray
    $pnpOutput = pnputil /delete-driver oem*.inf /uninstall /force
    Write-Host "   ✓ Old driver packages removed" -ForegroundColor Green
}
catch {
    Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
}
Write-Host ""
` : ''}

# Final Summary
Write-Host ""
Write-Host "╔════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║                  CLEANUP COMPLETE                       ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# Show current disk space
$disk = Get-PSDrive C
Write-Host "Drive C: Status:" -ForegroundColor Cyan
Write-Host "  Total Size: $([math]::Round(($disk.Used + $disk.Free) / 1GB, 2)) GB" -ForegroundColor White
Write-Host "  Used Space: $([math]::Round($disk.Used / 1GB, 2)) GB" -ForegroundColor White
Write-Host "  Free Space: $([math]::Round($disk.Free / 1GB, 2)) GB" -ForegroundColor Green
Write-Host ""
Write-Host "Total space freed: ~$([math]::Round($totalSpaceFreed / 1GB, 2)) GB" -ForegroundColor Green
Write-Host ""

Read-Host "Press Enter to exit"
`;

    const modalContent = `
        <div class="alert alert-warning">
            <span class="alert-icon">⚠️</span>
            <div>
                <strong>Disk Maintenance - Takes Time!</strong><br>
                This script performs deep system cleanup using DISM and other Windows tools. 
                <strong>It may take 10-20 minutes to complete.</strong> Do not interrupt the process!
            </div>
        </div>
        
        <div class="alert alert-success">
            <span class="alert-icon">✅</span>
            <div>
                <strong>Selected Cleanup Tasks:</strong><br>
                ${options.winsxs ? '✓ Clean Component Store (WinSxS) - 2-10 GB<br>' : ''}
                ${options.updates ? '✓ Remove Old Windows Updates - 1-5 GB<br>' : ''}
                ${options.logs ? '✓ Clear Old System Logs - 500 MB-2 GB<br>' : ''}
                ${options.drivers ? '✓ Remove Old Driver Packages - 200 MB-1 GB<br>' : ''}
                ${options.analyze ? '✓ Run Disk Cleanup Analysis First<br>' : ''}
                <br>
                <strong>Expected Total:</strong> 5-15 GB freed (typical)
            </div>
        </div>
        
        <h3>Script Preview:</h3>
        <div class="script-preview">${escapeHtml(script)}</div>
        
        <div class="btn-group">
            <button class="btn btn-success" onclick="downloadScript('DiskMaintenance_${getTimestamp()}.ps1', \`${script.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`)">
                💾 Download Script
            </button>
            <button class="btn btn-secondary" onclick="closeModal()">
                Close Preview
            </button>
        </div>
    `;
    
    showModal('💾 Disk Maintenance Script Ready', modalContent);
}

// ============================================
// COMPLETE OPTIMIZATION SUITE & SCHEDULED TASK
// ============================================

function generateCompleteScript() {
    // Implementation similar to others but with all safe defaults
    showNotification('✨ Generating complete optimization suite...', 'info');
    
    // TO BE COMPLETED: Add complete suite script
    showNotification('⚠️ This feature is being finalized. Use individual optimizations for now.', 'warning');
}

function generateScheduledTask() {
    // Implementation for weekly scheduled maintenance
    showNotification('⏰ Scheduled task generator coming soon...', 'info');
}

// Export functions for use in main optimizer.js
// These need to be merged or loaded together
